/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppArrows {
    'dataName': string;
    'direction': string;
    'selected': boolean;
    'text': string;
  }
  interface AppArrowsAttributes extends StencilHTMLAttributes {
    'dataName'?: string;
    'direction'?: string;
    'selected'?: boolean;
    'text'?: string;
  }

  interface AppBackdrop {
    'open': boolean;
  }
  interface AppBackdropAttributes extends StencilHTMLAttributes {
    'open'?: boolean;
  }

  interface AppInfoTable {
    'data': any;
  }
  interface AppInfoTableAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }

  interface AppModal {
    'closeButton': boolean;
    'closeButtonText': string;
    'confirmButton': boolean;
    'confirmButtonText': string;
    'modalTitle': string;
    'open': boolean;
  }
  interface AppModalAttributes extends StencilHTMLAttributes {
    'closeButton'?: boolean;
    'closeButtonText'?: string;
    'confirmButton'?: boolean;
    'confirmButtonText'?: string;
    'modalTitle'?: string;
    'onCloseModal'?: (event: CustomEvent) => void;
    'open'?: boolean;
  }

  interface AppPagination {
    'maxSeq': number;
    'nPage': number;
  }
  interface AppPaginationAttributes extends StencilHTMLAttributes {
    'maxSeq'?: number;
    'nPage'?: number;
    'onChangePage'?: (event: CustomEvent) => void;
  }

  interface AppTable {
    'bindData': (data: any) => void;
    'nrowPage': number;
  }
  interface AppTableAttributes extends StencilHTMLAttributes {
    'nrowPage'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppArrows': Components.AppArrows;
    'AppBackdrop': Components.AppBackdrop;
    'AppInfoTable': Components.AppInfoTable;
    'AppModal': Components.AppModal;
    'AppPagination': Components.AppPagination;
    'AppTable': Components.AppTable;
  }

  interface StencilIntrinsicElements {
    'app-arrows': Components.AppArrowsAttributes;
    'app-backdrop': Components.AppBackdropAttributes;
    'app-info-table': Components.AppInfoTableAttributes;
    'app-modal': Components.AppModalAttributes;
    'app-pagination': Components.AppPaginationAttributes;
    'app-table': Components.AppTableAttributes;
  }


  interface HTMLAppArrowsElement extends Components.AppArrows, HTMLStencilElement {}
  var HTMLAppArrowsElement: {
    prototype: HTMLAppArrowsElement;
    new (): HTMLAppArrowsElement;
  };

  interface HTMLAppBackdropElement extends Components.AppBackdrop, HTMLStencilElement {}
  var HTMLAppBackdropElement: {
    prototype: HTMLAppBackdropElement;
    new (): HTMLAppBackdropElement;
  };

  interface HTMLAppInfoTableElement extends Components.AppInfoTable, HTMLStencilElement {}
  var HTMLAppInfoTableElement: {
    prototype: HTMLAppInfoTableElement;
    new (): HTMLAppInfoTableElement;
  };

  interface HTMLAppModalElement extends Components.AppModal, HTMLStencilElement {}
  var HTMLAppModalElement: {
    prototype: HTMLAppModalElement;
    new (): HTMLAppModalElement;
  };

  interface HTMLAppPaginationElement extends Components.AppPagination, HTMLStencilElement {}
  var HTMLAppPaginationElement: {
    prototype: HTMLAppPaginationElement;
    new (): HTMLAppPaginationElement;
  };

  interface HTMLAppTableElement extends Components.AppTable, HTMLStencilElement {}
  var HTMLAppTableElement: {
    prototype: HTMLAppTableElement;
    new (): HTMLAppTableElement;
  };

  interface HTMLElementTagNameMap {
    'app-arrows': HTMLAppArrowsElement
    'app-backdrop': HTMLAppBackdropElement
    'app-info-table': HTMLAppInfoTableElement
    'app-modal': HTMLAppModalElement
    'app-pagination': HTMLAppPaginationElement
    'app-table': HTMLAppTableElement
  }

  interface ElementTagNameMap {
    'app-arrows': HTMLAppArrowsElement;
    'app-backdrop': HTMLAppBackdropElement;
    'app-info-table': HTMLAppInfoTableElement;
    'app-modal': HTMLAppModalElement;
    'app-pagination': HTMLAppPaginationElement;
    'app-table': HTMLAppTableElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
